const ITEM_DATABASE = {
  // 기존: 생명의구슬 로직
  applyLifeOrb(user, damage, battle) {
    const finalDamage = typeof damage === 'number' ? Math.floor(damage * 1.3) : damage;
    const recoil = (user && typeof user.max_hp === 'number') ? Math.max(1, Math.floor(user.max_hp * 0.1)) : null;

    if (battle && recoil != null) {
      if (typeof battle.applyRecoil === 'function') {
        battle.applyRecoil(user, recoil, "생명의구슬");
      } else if (user && typeof user.hp === 'number') {
        user.hp = Math.max(0, user.hp - recoil);
      }
    }
    return finalDamage;
  },

  // 신규: 구애 시리즈 로직 (공격/특공/스피드 1.5배 및 기술 고정 플래그)
  applyChoiceItem(user, statType) {
    if (user.stats && user.stats[statType]) {
      user.stats[statType] = Math.floor(user.stats[statType] * 1.5);
      user.flags.move_lock = true; // 게임 로직에서 첫 기술로 고정 처리
    }
  },

  // 신규: 자뭉열매 로직 (HP 50% 이하 시 25% 회복)
  applySitrusBerry(user, battle) {
    if (user.hp <= user.max_hp * 0.5) {
      const healAmount = Math.floor(user.max_hp * 0.25);
      user.hp = Math.min(user.max_hp, user.hp + healAmount);
      return true; // 사용됨 (소모 처리)
    }
    return false;
  },

  // 신규: 물리/특수 위력 강화 (힘의머리띠, 박식안경)
  applyCategoryBoost(move, damage, category) {
    if (move.category === category) {
      return Math.floor(damage * 1.1);
    }
    return damage;
  },

  applyLeftovers(user) { return user; },
  applyBlackSludge(user) { return user; },
  applyFocusSash(user) { return user; },
  applyGoodPotion(target) { return target; }
};

const ITEM_DATABASE_RAW = `
  choice_band {
    id choice_band,
    rank 1,
    name_ko 구애머리띠,
    name_en Choice Band,
    category 지닌물건,
    shape { kind band, css border-radius:4px;background:linear-gradient(135deg,#C0392B,#E74C3C);, primary_color #C0392B, secondary_color #E74C3C },
    description_ko 물리 공격력을 파격적으로 높이지만, 하나의 기술만 사용할 수 있게 됩니다.,
    description_en Boosts Attack by 1.5× but locks the user into one move.,
    battle_effect_ko 공격이 1.5배가 되지만 한 가지 기술밖에 쓸 수 없게 된다.,
    battle_effect_en Boosts Attack by 1.5×, but allows the use of only one move.,
    logic_name applyChoiceBand,
    logic_formula user.stats.atk = 1.5; user.flags.lock_move = true,
    effect ITEM_DATABASE.applyChoiceItem,
  },
  choice_specs {
    id choice_specs,
    rank 2,
    name_ko 구애안경,
    name_en Choice Specs,
    category 지닌물건,
    shape { kind glasses, css border-radius:12px;background:linear-gradient(135deg,#2980B9,#3498DB);, primary_color #2980B9, secondary_color #3498DB },
    description_ko 특수 공격력을 크게 강화하는 대신, 기술 선택에 제약이 생기는 상급자용 도구입니다.,
    description_en Boosts Sp. Atk by 1.5× but locks the user into one move.,
    battle_effect_ko 특수공격이 1.5배가 되지만 한 가지 기술밖에 쓸 수 없게 된다.,
    battle_effect_en Boosts Sp. Atk by 1.5×, but allows the use of only one move.,
    logic_name applyChoiceSpecs,
    logic_formula user.stats.spatk = 1.5; user.flags.lock_move = true,
    effect ITEM_DATABASE.applyChoiceItem,
  },
  choice_scarf {
    id choice_scarf,
    rank 3,
    name_ko 구애스카프,
    name_en Choice Scarf,
    category 지닌물건,
    shape { kind scarf, css border-radius:2px;background:linear-gradient(135deg,#27AE60,#2ECC71);, primary_color #27AE60, secondary_color #2ECC71 },
    description_ko 스피드를 폭발적으로 높여 선공권을 확보하지만, 기술이 하나로 고정됩니다.,
    description_en Boosts Speed by 1.5× but locks the user into one move.,
    battle_effect_ko 스피드가 1.5배가 되지만 한 가지 기술밖에 쓸 수 없게 된다.,
    battle_effect_en Boosts Speed by 1.5×, but allows the use of only one move.,
    logic_name applyChoiceScarf,
    logic_formula user.stats.spe = 1.5; user.flags.lock_move = true,
    effect ITEM_DATABASE.applyChoiceItem,
  },
  life_orb {
    id life_orb,
    rank 4,
    name_ko 생명의구슬,
    name_en Life Orb,
    category 지닌물건,
    shape { kind orb, css border-radius:999px;background:linear-gradient(135deg,#ECF0F1,#C0392B);, primary_color #ECF0F1, secondary_color #C0392B },
    description_ko 체력을 조금씩 소모하며 모든 기술의 위력을 강력하게 끌어올립니다.,
    description_en Boosts the power of moves but at the cost of some HP every turn.,
    battle_effect_ko 기술의 위력이 1.3배가 되지만 공격할 때마다 체력이 10% 줄어든다.,
    battle_effect_en Boosts move power by 1.3× at the cost of 10% max HP per attack.,
    logic_name applyLifeOrb,
    logic_formula finalDamage = 1.3; recoil = 0.1,
    effect ITEM_DATABASE.applyLifeOrb,
  },
  sitrus_berry {
    id sitrus_berry,
    rank 5,
    name_ko 자뭉열매,
    name_en Sitrus Berry,
    category 지닌물건,
    shape { kind berry, css border-radius:50% 50% 50% 50% / 60% 60% 40% 40%;background:linear-gradient(135deg,#F1C40F,#F39C12);, primary_color #F1C40F, secondary_color #F39C12 },
    description_ko 위급한 순간에 체력을 회복시켜 주는 배틀의 필수 생존 아이템입니다.,
    description_en A berry that restores HP when it falls below half.,
    battle_effect_ko 체력이 절반 이하가 되었을 때 최대 HP의 25%를 회복한다.,
    battle_effect_en Restores 25% of max HP when current HP is below 50%.,
    logic_name applySitrusBerry,
    logic_formula if hp <= 0.5 then hp += 0.25,
    effect ITEM_DATABASE.applySitrusBerry,
  },
  expert_belt {
    id expert_belt,
    rank 6,
    name_ko 달인의띠,
    name_en Expert Belt,
    category 지닌물건,
    shape { kind belt, css border-radius:999px;background:linear-gradient(135deg,#D35400,#A04000);, primary_color #D35400, secondary_color #A04000 },
    description_ko 상성 유리한 한 방을 더욱 아프게 만들어 주는 범용 딜 강화 아이템입니다.,
    description_en A versatile damage item that makes super-effective hits stronger.,
    battle_effect_ko 상성이 매우 유리한 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts super-effective moves by 1.2×.,
    logic_name applyExpertBelt,
    logic_formula if move.is_super_effective then final_damage = 1.2,
    effect ITEM_DATABASE.applyExpertBelt,
  },
  light_ball {
    id light_ball,
    rank 7,
    name_ko 전기구슬,
    name_en Light Ball,
    category 지닌물건,
    shape { kind sphere, css border-radius:999px;background:linear-gradient(135deg,#F7DC6F,#F1C40F);, primary_color #F7DC6F, secondary_color #F1C40F },
    description_ko 피카츄의 잠재력을 크게 끌어올리는 전용형 폭발 아이템입니다.,
    description_en A signature item that massively boosts Pikachu's power.,
    battle_effect_ko 피카츄가 지니면 공격과 특수공격이 크게 오른다.,
    battle_effect_en If held by Pikachu, Attack and Sp. Atk are greatly boosted.,
    logic_name applyLightBall,
    logic_formula if user.species == '피카츄' then user.stats.atk = 2; user.stats.spatk = 2,
    effect ITEM_DATABASE.applyLightBall,
  },
  air_balloon {
    id air_balloon,
    rank 8,
    name_ko 풍선,
    name_en Air Balloon,
    category 지닌물건,
    shape { kind balloon, css border-radius:999px;background:linear-gradient(135deg,#85C1E9,#D6EAF8);, primary_color #85C1E9, secondary_color #D6EAF8 },
    description_ko 땅 타입 기술을 잠시 막아 주는 기동성형 아이템입니다.,
    description_en A temporary immunity item against Ground-type attacks.,
    battle_effect_ko 땅 타입 기술에 맞기 전까지 땅 기술에 면역이 된다. 한 번 맞으면 터진다.,
    battle_effect_en Grants temporary immunity to Ground-type moves until hit; then it pops.,
    logic_name applyAirBalloon,
    logic_formula user.flags.ground_immune = true; on_damage(user) pop_balloon(user),
    effect ITEM_DATABASE.applyAirBalloon,
  },
  muscle_band {
    id muscle_band,
    rank 9,
    name_ko 힘의머리띠,
    name_en Muscle Band,
    category 지닌물건,
    shape { kind band, css border-radius:4px;background:linear-gradient(135deg,#7F8C8D,#34495E);, primary_color #7F8C8D, secondary_color #34495E },
    description_ko 물리 기술의 위력을 소폭 상승시켜 주는 안정적인 공격 보조 도구입니다.,
    description_en A headband that slightly boosts the power of physical moves.,
    battle_effect_ko 물리 기술의 위력이 1.1배가 된다.,
    battle_effect_en Boosts the power of physical moves by 1.1×.,
    logic_name applyMuscleBand,
    logic_formula if move.category == '물리' then final_damage = 1.1,
    effect ITEM_DATABASE.applyCategoryBoost,
  },
  wise_glasses {
    id wise_glasses,
    rank 10,
    name_ko 박식안경,
    name_en Wise Glasses,
    category 지닌물건,
    shape { kind glasses, css border-radius:8px;background:linear-gradient(135deg,#9B59B6,#8E44AD);, primary_color #9B59B6, secondary_color #8E44AD },
    description_ko 특수 기술의 위력을 소폭 높여 주는 지적인 디자인의 강화 아이템입니다.,
    description_en Glasses that slightly boost the power of special moves.,
    battle_effect_ko 특수 기술의 위력이 1.1배가 된다.,
    battle_effect_en Boosts the power of special moves by 1.1×.,
    logic_name applyWiseGlasses,
    logic_formula if move.category == '특수' then final_damage = 1.1,
    effect ITEM_DATABASE.applyCategoryBoost,
  },
  black_glasses {
    id black_glasses,
    rank 11,
    name_ko 검은안경,
    name_en Black Glasses,
    category 지닌물건,
    shape { kind glasses, css border-radius:16px;background:linear-gradient(135deg,#000000,#2C3E50);, primary_color #000000, secondary_color #2C3E50 },
    description_ko 악 타입 기술의 위력을 끌어올리는 단순 명료한 공격형 아이템입니다.,
    description_en A straightforward offensive item that boosts Dark-type moves.,
    battle_effect_ko 악 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Dark-type move damage by 1.2×.,
    logic_name applyBlackGlasses,
    logic_formula if move.type == '악' then final_damage = 1.2,
    effect ITEM_DATABASE.applyBlackGlasses,
  },
  black_belt {
    id black_belt,
    rank 12,
    name_ko 검은띠,
    name_en Black Belt,
    category 지닌물건,
    shape { kind belt, css border-radius:999px;background:linear-gradient(135deg,#111111,#566573);, primary_color #111111, secondary_color #566573 },
    description_ko 격투 포켓몬의 물리 압박을 높이는 기본 화력 아이템입니다.,
    description_en A basic power item for Fighting-type physical pressure.,
    battle_effect_ko 격투 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Fighting-type move damage by 1.2×.,
    logic_name applyBlackBelt,
    logic_formula if move.type == '격투' then final_damage = 1.2,
    effect ITEM_DATABASE.applyBlackBelt,
  },
  sharp_beak {
    id sharp_beak,
    rank 13,
    name_ko 예리한부리,
    name_en Sharp Beak,
    category 지닌물건,
    shape { kind beak, css border-radius:18px;background:linear-gradient(135deg,#F39C12,#D68910);, primary_color #F39C12, secondary_color #D68910 },
    description_ko 비행 기술의 위력을 안정적으로 올려 주는 대표 범용 보조 아이템입니다.,
    description_en A common offensive item that boosts Flying-type moves.,
    battle_effect_ko 비행 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Flying-type move damage by 1.2×.,
    logic_name applySharpBeak,
    logic_formula if move.type == '비행' then final_damage = 1.2,
    effect ITEM_DATABASE.applySharpBeak,
  },
  charcoal {
    id charcoal,
    rank 14,
    name_ko 목탄,
    name_en Charcoal,
    category 지닌물건,
    shape { kind charcoal, css border-radius:16px;background:linear-gradient(135deg,#5D4037,#2E2E2E);, primary_color #5D4037, secondary_color #2E2E2E },
    description_ko 불꽃 기술의 화력을 올리는 전통적인 불 타입 강화 아이템입니다.,
    description_en A traditional Fire-type damage booster.,
    battle_effect_ko 불 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Fire-type move damage by 1.2×.,
    logic_name applyCharcoal,
    logic_formula if move.type == '불' then final_damage = 1.2,
    effect ITEM_DATABASE.applyCharcoal,
  },
  mystic_water {
    id mystic_water,
    rank 15,
    name_ko 신비의물방울,
    name_en Mystic Water,
    category 지닌물건,
    shape { kind droplet, css border-radius:999px;background:linear-gradient(135deg,#2980B9,#1F618D);, primary_color #2980B9, secondary_color #1F618D },
    description_ko 물 타입 포켓몬의 안정적 딜링을 돕는 기본적인 공격 아이템입니다.,
    description_en A basic damage item that strengthens Water-type attacks.,
    battle_effect_ko 물 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Water-type move damage by 1.2×.,
    logic_name applyMysticWater,
    logic_formula if move.type == '물' then final_damage = 1.2,
    effect ITEM_DATABASE.applyMysticWater,
  },
  miracle_seed {
    id miracle_seed,
    rank 16,
    name_ko 기적의씨,
    name_en Miracle Seed,
    category 지닌물건,
    shape { kind seed, css border-radius:999px;background:linear-gradient(135deg,#7DCEA0,#27AE60);, primary_color #7DCEA0, secondary_color #27AE60 },
    description_ko 풀 타입 기술의 데미지를 올려 주는 범용적인 타입 강화 씨앗입니다.,
    description_en A type-boosting seed that strengthens Grass-type moves.,
    battle_effect_ko 풀 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Grass-type move damage by 1.2×.,
    logic_name applyMiracleSeed,
    logic_formula if move.type == '풀' then final_damage = 1.2,
    effect ITEM_DATABASE.applyMiracleSeed,
  },
  poison_barb {
    id poison_barb,
    rank 17,
    name_ko 독바늘,
    name_en Poison Barb,
    category 지닌물건,
    shape { kind needle, css border-radius:16px;background:linear-gradient(135deg,#8E44AD,#6C3483);, primary_color #8E44AD, secondary_color #6C3483 },
    description_ko 독 타입 기술의 위력을 올리고, 독 컨셉 포켓몬과 잘 맞는 공격형 물건입니다.,
    description_en An offensive Poison-type item that improves poison pressure.,
    battle_effect_ko 독 기술의 최종 데미지를 1.2배로 올린다.,
    battle_effect_en Boosts Poison-type move damage by 1.2×.,
    logic_name applyPoisonBarb,
    logic_formula if move.type == '독' then final_damage = 1.2,
    effect ITEM_DATABASE.applyPoisonBarb,
  },
  zoom_lens {
    id zoom_lens,
    rank 18,
    name_ko 광각렌즈,
    name_en Zoom Lens,
    category 지닌물건,
    shape { kind lens, css border-radius:999px;background:linear-gradient(135deg,#AED6F1,#5DADE2);, primary_color #AED6F1, secondary_color #5DADE2 },
    description_ko 후공 상황에서 명중률을 끌어올려, 느린 포켓몬의 답답함을 완화합니다.,
    description_en Improves accuracy when the holder moves after the target.,
    battle_effect_ko 나중에 행동할 때 명중률이 20% 오른다.,
    battle_effect_en Raises accuracy by 20% if the user acts after the target.,
    logic_name applyZoomLens,
    logic_formula if user.moves_after(target) then move.accuracy = 1.2,
    effect ITEM_DATABASE.applyZoomLens,
  },

  leftovers {
    id leftovers,
    rank 19,
    name_ko 먹다남은음식,
    name_en Leftovers,
    category 지닌물건,
    shape { kind food, css border-radius:14px;background:linear-gradient(135deg,#F7DC6F,#B7950B);, primary_color #F7DC6F, secondary_color #B7950B },
    description_ko 매 턴 종료 시 체력을 조금 회복하는 안정적인 생존용 지닌물건입니다.,
    description_en A durable held item that restores a small amount of HP every turn.,
    battle_effect_ko 매 턴 종료 시 최대 HP의 1/16을 회복한다.,
    battle_effect_en Restores 1/16 of max HP at the end of each turn.,
    logic_name applyLeftovers,
    logic_formula heal = max_hp / 16 on end_turn,
    effect ITEM_DATABASE.applyLeftovers,
  },
  black_sludge {
    id black_sludge,
    rank 20,
    name_ko 검은진흙,
    name_en Black Sludge,
    category 지닌물건,
    shape { kind sludge, css border-radius:14px;background:linear-gradient(135deg,#2C3E50,#6C3483);, primary_color #2C3E50, secondary_color #6C3483 },
    description_ko 독 타입에게는 회복을, 그 외 포켓몬에게는 피해를 주는 개성적인 지닌물건입니다.,
    description_en A unique held item that heals Poison-types and damages others.,
    battle_effect_ko 독 타입이면 매 턴 최대 HP의 1/16을 회복하고, 아니면 1/8 피해를 입는다.,
    battle_effect_en Heals Poison-types by 1/16 max HP each turn; otherwise deals 1/8 damage.,
    logic_name applyBlackSludge,
    logic_formula if poison_type heal max_hp/16 else damage max_hp/8 on end_turn,
    effect ITEM_DATABASE.applyBlackSludge,
  },
  focus_sash {
    id focus_sash,
    rank 21,
    name_ko 기합의띠,
    name_en Focus Sash,
    category 지닌물건,
    shape { kind sash, css border-radius:6px;background:linear-gradient(135deg,#F8F9F9,#E74C3C);, primary_color #F8F9F9, secondary_color #E74C3C },
    description_ko 풀피 상태에서 쓰러질 피해를 한 번 1HP로 버티게 해 주는 위기 대응형 지닌물건입니다.,
    description_en Lets the holder survive a knockout hit at 1 HP once from full health.,
    battle_effect_ko HP가 가득 찬 상태에서 쓰러질 피해를 입으면 한 번 1HP로 버틴다.,
    battle_effect_en If at full HP, survives a would-be knockout hit with 1 HP once.,
    logic_name applyFocusSash,
    logic_formula if full_hp and lethal_damage then survive_at_1hp_once,
    effect ITEM_DATABASE.applyFocusSash,
  },
  good_potion {
    id good_potion,
    rank null,
    name_ko 좋은상처약,
    name_en Good Potion,
    category 소비아이템,
    shape { kind bottle, css border-radius:14px;background:linear-gradient(135deg,#58D68D,#27AE60);, primary_color #58D68D, secondary_color #27AE60 },
    description_ko 포켓몬의 HP를 60 회복하는 범용 회복 아이템입니다.,
    description_en A reliable recovery item that restores 60 HP.,
    use_effect_ko 선택한 포켓몬의 HP를 60 회복한다.,
    use_effect_en Restores 60 HP to the selected Pokémon.,
    battle_effect_ko 전투 중 선택한 포켓몬의 HP를 60 회복한다.,
    battle_effect_en Restores 60 HP to the selected Pokémon in battle.,
    logic_name applyGoodPotion,
    logic_formula target.hp = min(target.max_hp, target.hp + 60),
    useEffect ITEM_DATABASE.applyGoodPotion,
  },
  paralyze_heal {
    id paralyze_heal,
    rank null,
    name_ko 마비치료제,
    name_en Paralyze Heal,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#F4D03F,#D4AC0D);, primary_color #F4D03F, secondary_color #D4AC0D },
    description_ko 포켓몬의 마비 상태를 치료하는 기본 상태 치료 아이템입니다.,
    description_en A basic status item that cures paralysis.,
    use_effect_ko 선택한 포켓몬의 마비 상태를 치료한다.,
    use_effect_en Cures paralysis on the selected Pokémon.,
    logic_name cureParalysis,
    logic_formula if target.status == '마비' then target.status = null,
    useEffect ITEM_DATABASE.cureParalysis,
  },
  antidote {
    id antidote,
    rank null,
    name_ko 해독제,
    name_en Antidote,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#58D68D,#239B56);, primary_color #58D68D, secondary_color #239B56 },
    description_ko 독 상태를 치료하는 기본적인 상태 회복 아이템입니다.,
    description_en A basic item that cures poison.,
    use_effect_ko 선택한 포켓몬의 독 상태를 치료한다.,
    use_effect_en Cures poison on the selected Pokémon.,
    logic_name curePoison,
    logic_formula if target.status == '독' then target.status = null,
    useEffect ITEM_DATABASE.curePoison,
  },
  burn_heal {
    id burn_heal,
    rank null,
    name_ko 화상치료제,
    name_en Burn Heal,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#E74C3C,#A93226);, primary_color #E74C3C, secondary_color #A93226 },
    description_ko 화상으로 인한 지속 피해와 공격 약화를 해소하는 아이템입니다.,
    description_en An item that cures burn status.,
    use_effect_ko 선택한 포켓몬의 화상 상태를 치료한다.,
    use_effect_en Cures burn on the selected Pokémon.,
    logic_name cureBurn,
    logic_formula if target.status == '화상' then target.status = null,
    useEffect ITEM_DATABASE.cureBurn,
  },
  ice_heal {
    id ice_heal,
    rank null,
    name_ko 얼음치료제,
    name_en Ice Heal,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#5DADE2,#2E86C1);, primary_color #5DADE2, secondary_color #2E86C1 },
    description_ko 얼음 상태를 해제하는 상태 회복 아이템입니다.,
    description_en An item that cures freeze.,
    use_effect_ko 선택한 포켓몬의 얼음 상태를 치료한다.,
    use_effect_en Cures freeze on the selected Pokémon.,
    logic_name cureFreeze,
    logic_formula if target.status == '얼음' then target.status = null,
    useEffect ITEM_DATABASE.cureFreeze,
  },
  awakening_spray {
    id awakening_spray,
    rank null,
    name_ko 잠깨는약,
    name_en Awakening Spray,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#A569BD,#7D3C98);, primary_color #A569BD, secondary_color #7D3C98 },
    description_ko 잠듦 상태를 풀어 다음 턴 행동을 가능하게 하는 아이템입니다.,
    description_en An item that wakes a sleeping Pokémon.,
    use_effect_ko 선택한 포켓몬의 잠듦 상태를 치료한다.,
    use_effect_en Cures sleep on the selected Pokémon.,
    logic_name cureSleep,
    logic_formula if target.status == '잠듦' then target.status = null,
    useEffect ITEM_DATABASE.cureSleep,
  },
  revive_shard {
    id revive_shard,
    rank null,
    name_ko 기력의조각,
    name_en Revive Shard,
    category 소비아이템,
    shape { kind shard, css border-radius:10px;transformskew(-12deg);background:linear-gradient(135deg,#D5DBDB,#7F8C8D);, primary_color #D5DBDB, secondary_color #7F8C8D },
    description_ko 쓰러진 포켓몬을 다시 전투에 세울 수 있게 해 주는 부활용 조각입니다.,
    description_en A revival shard that brings a fainted Pokémon back into battle.,
    use_effect_ko 쓰러진 포켓몬을 최대 HP의 50% 상태로 부활시킨다.,
    use_effect_en Revives a fainted Pokémon with 50% of its max HP.,
    logic_name reviveShard,
    logic_formula if target.hp = 0 then target.hp = floor(target.max_hp * 0.5); target.status = null,
    useEffect ITEM_DATABASE.reviveShard,
  },
  rare_candy {
    id rare_candy,
    rank null,
    name_ko 이상한사탕,
    name_en Rare Candy,
    category 특수 도구,
    shape { kind candy, css border-radius:999px;background:linear-gradient(135deg,#F5B7B1,#CD6155);, primary_color #F5B7B1, secondary_color #CD6155 },
    description_ko 포켓몬의 레벨을 1 올려 주는 핵심 성장 아이템입니다. 최대 레벨은 100입니다.,
    description_en A key growth item that raises one Pokémon's level by 1, up to level 100.,
    use_effect_ko 선택한 포켓몬의 레벨을 1 올린다. 최대 100레벨.,
    use_effect_en Raises the selected Pokémon's level by 1. Max level 100.,
    logic_name rareCandy,
    logic_formula target.level = min(100, target.level + 1); recalc_stats(target); auto_evolve_if_needed(target),
    useEffect ITEM_DATABASE.rareCandy,
  },
  reset_herb {
    id reset_herb,
    rank null,
    name_ko 능력치리셋약,
    name_en Reset Herb,
    category 소비아이템,
    shape { kind herb, css border-radius:14px;background:linear-gradient(135deg,#F7F9F9,#D5DBDB);, primary_color #F7F9F9, secondary_color #D5DBDB },
    description_ko 전투 중 쌓인 능력치 단계 변화를 초기화하는 정리형 아이템입니다.,
    description_en A cleanup item that resets temporary stat stage changes.,
    use_effect_ko 선택한 포켓몬의 능력치 변화 단계를 초기화한다.,
    use_effect_en Resets the selected Pokémon's temporary stat stage changes.,
    logic_name resetModifiers,
    logic_formula clear_stat_stage_changes(target); clear_temporary_buffs(target),
    useEffect ITEM_DATABASE.resetModifiers,
  },
  PP_aide {
    id PP_aide,
    rank null,
    name_ko PP에이드,
    name_en PP Aide,
    category 소비아이템,
    shape { kind capsule, css border-radius:14px;background:linear-gradient(135deg,#7D3C98,#9B59B6);, primary_color #7D3C98, secondary_color #9B59B6 },
    description_ko 포켓몬의 기술 1개의 PP를 10만큼 회복시키는 배틀용 소모 아이템입니다.,
    description_en A battle item that restores 10 PP to one selected move.,
    use_effect_ko 선택한 포켓몬의 기술 1개의 PP를 10 회복한다. 최대 PP를 넘길 수 없다.,
    use_effect_en Restores 10 PP to one selected move. It cannot exceed the move's max PP.,
    battle_effect_ko 선택한 기술의 PP를 10 회복하며, 이미 PP가 가득 찬 기술에는 사용할 수 없다.,
    battle_effect_en Restores 10 PP to a selected move. It fails if the move is already at full PP.,
    logic_name applyPPEide,
    logic_formula target.move.pp = min(target.move.max_pp, target.move.pp + 10),
    useEffect ITEM_DATABASE.applyPPEide,
  },
`;

if (typeof window !== 'undefined') {
  window.ITEM_DATABASE = ITEM_DATABASE;
  window.ITEM_DATABASE_RAW = ITEM_DATABASE_RAW;
}
